const WEEK=[{v:1,s:'周一'},{v:2,s:'周二'},{v:3,s:'周三'},{v:4,s:'周四'},{v:5,s:'周五'},{v:6,s:'周六'},{v:7,s:'周日'}];
const $=id=>document.getElementById(id);let schedules=[],selected=today();
function today(){const d=new Date();return dateStr(d)}function dateStr(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}function parse(s){const[a,b,c]=s.split('-').map(Number);return new Date(a,b-1,c,12)}function wd(s){const n=parse(s).getDay();return n||7}function shift(s,n){const d=parse(s);d.setDate(d.getDate()+n);return dateStr(d)}function week(s){const d=parse(s);d.setDate(d.getDate()-(wd(s)-1));return WEEK.map((w,i)=>{const x=new Date(d);x.setDate(d.getDate()+i);return{...w,date:dateStr(x),md:`${x.getMonth()+1}/${x.getDate()}`}})}function kind(x){return x.kind==='temporary'?'temporary':'fixed'}function rows(date){return schedules.filter(x=>kind(x)==='fixed'?Number(x.day)===wd(date):x.date===date).sort((a,b)=>a.startTime.localeCompare(b.startTime))}
function render(){const cfg=TrainLogCloud.getConfig();$('status').textContent=TrainLogCloud.hasSession()?`已连接共享课表 · ${cfg.email||''} · 数据仅同步课表`:'尚未登录共享课表。点击“连接设置”完成登录。';if(!TrainLogCloud.hasSession()){$('app').innerHTML='<div class="empty">请先连接共享课表。</div>';return}const days=week(selected),rs=rows(selected);$('app').innerHTML=`<div class="weeknav"><button class="secondary" id="prev">‹ 上一周</button><div class="notice summary" style="margin:0;text-align:center">${days[0].date} — ${days[6].date}</div><button class="secondary" id="now">本周</button><button class="secondary" id="next">下一周 ›</button></div><div class="weekdays">${days.map(d=>`<button class="day ${d.date===selected?'active':''}" data-date="${d.date}"><span>${d.s}</span><small>${d.md} · ${rows(d.date).length}节</small></button>`).join('')}</div><div class="list">${rs.length?rs.map(card).join(''):'<div class="empty">当天暂无课程</div>'}</div>`;$('prev').onclick=()=>{selected=shift(selected,-7);render()};$('next').onclick=()=>{selected=shift(selected,7);render()};$('now').onclick=()=>{selected=today();render()};document.querySelectorAll('.day').forEach(b=>b.onclick=()=>{selected=b.dataset.date;render()});document.querySelectorAll('.course').forEach(b=>b.onclick=()=>openCourse(schedules.find(x=>x.id===b.dataset.id)));}
function card(x){return `<button class="card course" data-id="${x.id}"><div class="time"><strong>${x.startTime}</strong><small>${x.endTime}</small></div><div class="meta"><h3>${esc(x.studentName)}</h3><p>${esc(x.type||'常规训练')}${x.notes?` · ${esc(x.notes)}`:''}</p></div><span class="tag ${kind(x)==='temporary'?'temp':''}">${kind(x)==='temporary'?'临时约课':'固定课'}</span></button>`}function esc(v){const d=document.createElement('div');d.textContent=v??'';return d.innerHTML}
function toggleFields(){$('fixedField').style.display=$('kind').value==='fixed'?'':'none';$('tempField').style.display=$('kind').value==='temporary'?'':'none'}
function fillNames(){$('studentNames').innerHTML=[...new Set(schedules.map(x=>x.studentName).filter(Boolean))].sort().map(n=>`<option value="${esc(n)}">`).join('')}
function openCourse(x=null){fillNames();$('courseTitle').textContent=x?'编辑课程':'安排课程';$('courseId').value=x?.id||'';$('kind').value=kind(x||{});$('studentName').value=x?.studentName||'';$('weekday').value=x?.day||wd(selected);$('courseDate').value=x?.date||selected;$('startTime').value=x?.startTime||'16:00';$('endTime').value=x?.endTime||'17:00';$('courseType').value=x?.type||'综合';$('notes').value=x?.notes||'';$('deleteBtn').classList.toggle('hidden',!x);toggleFields();$('courseDialog').showModal()}
async function load(){try{schedules=await TrainLogCloud.listSchedules();render()}catch(e){$('status').textContent='同步失败：'+e.message;render()}}
$('kind').onchange=toggleFields;$('addBtn').onclick=()=>TrainLogCloud.hasSession()?openCourse():$('loginDialog').showModal();$('settingsBtn').onclick=()=>{const c=TrainLogCloud.getConfig();$('url').value=c.url||'';$('key').value=c.key||'';$('email').value=c.email||'';$('password').value='';$('loginDialog').showModal()};$('cancelLogin').onclick=()=>$('loginDialog').close();$('cancelCourse').onclick=()=>$('courseDialog').close();
$('loginForm').onsubmit=async e=>{e.preventDefault();try{TrainLogCloud.setConfig({url:$('url').value,key:$('key').value,email:$('email').value});if($('password').value)await TrainLogCloud.signIn($('email').value,$('password').value);else if(!TrainLogCloud.hasSession())throw new Error('请输入密码完成首次登录');$('loginDialog').close();await load()}catch(err){alert('连接失败：'+err.message)}};
$('courseForm').onsubmit=async e=>{e.preventDefault();const x={studentName:$('studentName').value.trim(),kind:$('kind').value,day:$('kind').value==='fixed'?Number($('weekday').value):null,date:$('kind').value==='temporary'?$('courseDate').value:'',startTime:$('startTime').value,endTime:$('endTime').value,type:$('courseType').value,notes:$('notes').value.trim()};if(!x.studentName)return alert('请输入学员姓名');if(x.endTime<=x.startTime)return alert('结束时间需要晚于开始时间');if(x.kind==='temporary'&&!x.date)return alert('临时约课需要选择日期');try{const id=$('courseId').value;if(id)await TrainLogCloud.updateSchedule(id,x);else await TrainLogCloud.createSchedule(x);$('courseDialog').close();await load()}catch(err){alert('保存失败：'+err.message)}};
$('deleteBtn').onclick=async()=>{const id=$('courseId').value;if(!id||!confirm('确定删除这节课程？'))return;try{await TrainLogCloud.deleteSchedule(id);$('courseDialog').close();await load()}catch(err){alert('删除失败：'+err.message)}};
$('weekday').innerHTML=WEEK.map(x=>`<option value="${x.v}">${x.s}</option>`).join('');
if(TrainLogCloud.isConfigured()&&TrainLogCloud.hasSession())load();else render();
